version: '3'

services:
    elasticsearch:
      image: elasticsearch:v7.3.2
      container_name: elasticsearch
      hostname: elasticsearch
      environment:
        discovery.type: single-node
      ports:
        - 9200:9200
        - 9300:9300
      volumes:
        - ./configmap/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./data-dir/elasticsearch:/usr/share/elasticsearch/data
    kibana:
      image: kibana:7.3.2
      container_name: kibana
      hostname: kibana
      links:
        - elasticsearch
      ports:
        - 5601:5601
      volumes:
        - ./configmap/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml